hydra:
  searchpath:
    - file://verl/trainer/config

defaults:
  - ppo_trainer
  - _self_

data:
  max_prompt_length: 1024
  max_response_length: 512
  train_batch_size: 256
  return_raw_chat: True

actor_rollout_ref:
  hybrid_engine: True
  rollout:
    name: sglang
    multi_turn:
      enable: True
      max_user_turns: 5

envs:
  env_name: babaisai
  task: env/two_room-maybe_break_stop-goto_win
  format_penalty: 0.1
  binary_reward: true
  captioner:
    type: cot
    max_text_history: 1
    max_cot_history: 1
    max_image_history: 0
  babyai_kwargs:
    num_dists: 0
    # max_steps: 64
  babaisai_kwargs: 
    add_ruleset: True
  crafter_kwargs:
    area: [64, 64]              
    view: [9, 9]            
    size: [256, 256] # Image size in Crafter
    reward: True                       
    seed: null                  
    max_episode_steps: 2000  
  minihack_kwargs: 
    character: "@"
    max_episode_steps: 100
    penalty_step: -0.01         
    penalty_time: 0.0           
    penalty_mode: constant      
    savedir: null
    save_ttyrec_every: 0
    autopickup: False           
    skip_more: True